[project]
name = "project"
version = "0.1.0"
description = "First attempt at an AI Agent"
readme = "README.md"
authors = [
    { name = "BradJen18", email = "Jen22041@byui.edu" }
]
requires-python = ">=3.13"
dependencies = [
    "langchain>=1.4.2",
    "langchain-google-genai>=4.4.0",
    "python-dotenv>=1.2.3",
]

[project.scripts]
project = "project:main"

[build-system]
requires = ["uv_build>=0.12.18,<0.13.0"]
build-backend = "uv_build"
